//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("174, 126")]
        public global::System.Drawing.Point orta {
            get {
                return ((global::System.Drawing.Point)(this["orta"]));
            }
            set {
                this["orta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("164, 126")]
        public global::System.Drawing.Point ff {
            get {
                return ((global::System.Drawing.Point)(this["ff"]));
            }
            set {
                this["ff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("185, 126")]
        public global::System.Drawing.Point cc {
            get {
                return ((global::System.Drawing.Point)(this["cc"]));
            }
            set {
                this["cc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("188, 150")]
        public global::System.Drawing.Point ccc {
            get {
                return ((global::System.Drawing.Point)(this["ccc"]));
            }
            set {
                this["ccc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("190, 180")]
        public global::System.Drawing.Point qq {
            get {
                return ((global::System.Drawing.Point)(this["qq"]));
            }
            set {
                this["qq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("186, 195")]
        public global::System.Drawing.Point ortaa {
            get {
                return ((global::System.Drawing.Point)(this["ortaa"]));
            }
            set {
                this["ortaa"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("186, 205")]
        public global::System.Drawing.Point tam {
            get {
                return ((global::System.Drawing.Point)(this["tam"]));
            }
            set {
                this["tam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("186, 208")]
        public global::System.Drawing.Point ortapencere {
            get {
                return ((global::System.Drawing.Point)(this["ortapencere"]));
            }
            set {
                this["ortapencere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("186, 212")]
        public global::System.Drawing.Point ortakpencere {
            get {
                return ((global::System.Drawing.Point)(this["ortakpencere"]));
            }
            set {
                this["ortakpencere"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("186, 215")]
        public global::System.Drawing.Point ortak {
            get {
                return ((global::System.Drawing.Point)(this["ortak"]));
            }
            set {
                this["ortak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1103, 400")]
        public global::System.Drawing.Point Hesapmakinesi {
            get {
                return ((global::System.Drawing.Point)(this["Hesapmakinesi"]));
            }
            set {
                this["Hesapmakinesi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1103, 400")]
        public global::System.Drawing.Point Hesapmkn {
            get {
                return ((global::System.Drawing.Point)(this["Hesapmkn"]));
            }
            set {
                this["Hesapmkn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point oıu {
            get {
                return ((global::System.Drawing.Point)(this["oıu"]));
            }
            set {
                this["oıu"] = value;
            }
        }
    }
}
